[package]
name = "mycjson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_cjson"
crate-type = ["staticlib"]
path = "src/mycjson.rs"
[dependencies]
libc = "0.2"
